### ISSUE TITLE
DMARC configuration is incomplete

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#108]
https://mxtoolbox.com/SuperTool.aspx?action=dmarc%3akiwix.org&run=toolpage

Considering DMARC is at the core of the antispam fight, it seems important to me to complete its configuration

**Comment by benoit74** [comment]
DMARC is configured but very permissive

We have to set it up properly for all our service providers, list to be confirmed first (see https://github.com/kiwix/k8s/issues/87). A quick look seems to indicate that Gaggle has no idea about how to do it.

**Comment by rgaudin** [comment]
Indeed it's very permissive. I previously configured it to receive the aggregated reports myself and those were satisfying.
I just changed it to a stricter version (quarantine though), which will have two consequences:
- increase our domain's _reputation_
- have emails sent incorrectly be marked as spam **(very)** likely.

@Popolechien please make sure every person sending email via an `@kiwix.org` address has their setup OK.
They should be using Gandi's SMTP server (`mail.gandi.net` -- [the doc](https://docs.gandi.net/en/gandimail/standard_email_settings/index.html#smtp-account))

Another consequence is for people using a **redirection to another email, without a mailbox**. I count only 3 of them at the moment. They wont be able to send as their @kiwix.org address anymore (can send but likely marked as spam)

https://dmarcly.com/tools/dmarc-checker
