### ISSUE TITLE
Service without active endpoint

### ISSUE THREAD

**Issue by benoit74** [kiwix/k8s#116]
Nginx ingress is complaining about services without active endpoints (don't know why it is looking after all services ... anyway)

```
│ W0901 08:23:57.056456       8 controller.go:1076] Service "zim/library-service" does not have any active Endpoint.                                                                                                                         
│ W0901 08:23:57.056611       8 controller.go:1076] Service "wikifundi/wukifundi-fr-service" does not have any active Endpoint.                                                                                                              
│ W0901 08:23:57.056668       8 controller.go:1076] Service "cluster-mgmt/overview-service" does not have any active Endpoint.
```

The first one looks like a left-overs of service renaming 
The second one looks like a left-overs of service name typo fix + looks like nothing is deployed anymore in `wikifundi` 
The third one looks like a left-over of `cluster-mgmt` removal (namespace looks like empty)

@rgaudin : ok for you if I delete them next monday / when prod is stable ?

**Comment by rgaudin** [comment]
- `zim/library-service`: leftover of revamp
- `wikifundi/wukifundi-fr-service` lefover following typo fix
- `cluster-mgmt/overview-service` it's a mostly useless now service that used to run on bastion. it was scaled down to zero and deployment delete

You can remove all of them ; thank you

**Comment by benoit74** [comment]
Done
