### ISSUE TITLE
Introduce stats of library.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#17]
But only the catalogue part

**Comment by rgaudin** [comment]
You mean URLs with `/catalog/` prefix?

**Comment by kelson42** [comment]
@rgaudin I guess so, but not 100% sure. Considering that we will have a dedicated container... then just take the log of that one.

**Comment by rgaudin** [comment]
Done. Shall be visible on matomo after logrotate and upload_log.
