### ISSUE TITLE
[URGENT] Invalid certificate delivered by https://mirror.download.kiwix.org?

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#175]
Why the certificate #2 is invalid? Why two certificates! https://www.ssllabs.com/ssltest/analyze.html?d=mirror.download.kiwix.org

**Comment by rgaudin** [comment]
Certificate #2 is node-wide cert that is not advertised for this domain. It has no impact on that linked issue.

Root cause is explained in linked ticket. See a22b7f1 to revert it in ~1y.
