### ISSUE TITLE
Library.xml not http compressed

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#18]
http://download.kiwix.org/library/library_zim.xml

With

https://www.whatsmyip.org/http-compression-test/

**Comment by rgaudin** [comment]
Fixed. Please use http://mirror.download.kiwix.org/library/library_zim.xml whenever testing this as not all mirrors have gzip compression enabled for this file. Namely:

- ftp.nluug.nl
- mirrors.dotsrc.org
