### ISSUE TITLE
Upload `assetLinks.json` file on `download.kiwix.org` for deep linking in android.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/k8s#190]
For https://github.com/kiwix/kiwix-android/issues/3808 we require to upload the `assetLinks.json` file in `.well-known` folder on `download.kiwix.org` with read access to everyone. See https://developer.android.com/studio/write/app-link-indexing#associatesite.

![Screenshot from 2024-05-07 19-16-35](https://github.com/kiwix/k8s/assets/34593983/44ce8666-5632-4aee-833a-8868c29799e0)

[assetlinks.json](https://github.com/kiwix/k8s/files/15244313/assetlinks.json)

**Comment by MohitMaliFtechiz** [comment]
@benoit74, @rgaudin Can you please upload this `assetLinks.json` file?

**Comment by rgaudin** [comment]
@MohitMaliFtechiz there's a discrepancy between your request and the screenshot.

I am assuming the screenshot URL is right so please check https://download.kiwix.org/.well-known/assetlinks.json

**Comment by MohitMaliFtechiz** [comment]
@rgaudin Thanks, the file is uploaded at the right place.

![Screenshot from 2024-05-08 15-28-37](https://github.com/kiwix/k8s/assets/34593983/827d69a1-fbd2-4e8b-b39e-91b5eeba4776)
