### ISSUE TITLE
developer.mozilla.org ZIM missing from library.kiwix.org

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/k8s#24]
I can't find a way to load `developer.mozilla.org_en_all_2022-03.zim` in library.kiwix.org. It appears to be missing, but it is available in download.kiwix.org (zimit directory).

Can it be added? It's very useful!

**Comment by rgaudin** [comment]
@Jaifroid it is present now. I can't say why as I did nothing – and I didn't properly checked but I believe you did– but to save the output of the script to a log file to check… 😅

https://library.kiwix.org/developer.mozilla.org_en_all_2022-03/

We've recently rewrote the script that generates the library so in case of any doubt, please open a ticket here.

**Comment by Jaifroid** [comment]
Thanks, @kelson42 I confirm it is there! I must have got confused by not finding anything when searching for "mozilla" or for "developer.mozilla.org". Should it not appear when searching by zim filename?

Two points that would help in discoverability (I realize they are probably separate issues, but clearly the search had me confused...):

- Show filename in the tiles along with description. It is really hard to find a specific ZIM otherwise, especially when searching for "Wikipedia", where you might have different files published on different dates, but they look exactly the same;
- Allow searching on (significant parts of) filename -- helps regular user who knows which file they want to update;
- Show the **date** of the ZIM on the tile (though if the filename is there, it might not be necessary).

**Comment by kelson42** [comment]
> Should it not appear when searching by zim filename?

Probably, see again my comment at https://github.com/kiwix/libkiwix/issues/599

> * Show filename in the tiles along with description. It is really hard to find a specific ZIM otherwise, especially when searching for "Wikipedia", where you might have different files published on different dates, but they look exactly the same;

I think the problem of differentiation between multiple Wikipedia tiles is a real one. But I don't believe putting a technical information like the filename is a good idea. But we should have a way to differentiate the flavours (like we have already in a few Kiwix readers). One of the problem with Wikipedia is that the description is not always really helpful.

> * Allow searching on (significant parts of) filename -- helps regular user who knows which file they want to update;

This should automatically work if the filename is taken in account in the search like requested at https://github.com/kiwix/libkiwix/issues/599. This already works like this (if you type "dev" for example).

> * Show the **date** of the ZIM on the tile (though if the filename is there, it might not be necessary).

This is an idea, I don't have a strong opinion on this. I would recommend to make your point in a dedicated ticket on kiwix/kiwix-tools.
