### ISSUE TITLE
Mathoverflow not updated on library.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#27]
https://library.kiwix.org/?lang=&q=Mathoverflow Still delivers a version of 2021 although wwe have publiahed a new version yesterday.

**Comment by rgaudin** [comment]
Fixed ; thanks. You'll notice there are now two entries for it. That's due partly to https://github.com/openzim/sotoki/commit/ab9f1e86fa830c871aa6b2225c09c9258a313a1d and the fact that I haven't cleaned up stack exchange files in the repo.
