### ISSUE TITLE
No stats anymore for download.kiwix.org since 4 days

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#28]
https://stats.kiwix.org/index.php?module=CoreHome&action=index&idSite=2&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1&idSite=2

**Comment by rgaudin** [comment]
Fixed! Thanks for the report. We really need to setup some k8s monitoring.

**Comment by kelson42** [comment]
Seems again dead.

**Comment by rgaudin** [comment]
Fixed again ; sorry
