### ISSUE TITLE
Add nodes logrotate

### ISSUE THREAD

**Issue by rgaudin** [kiwix/k8s#3]
All containers' logs are stored on their node's filesystem, growing forever.
This can quickly become problematic.

To implement this, we need to define how much log we want to keep.
@kelson42 what do you think?

[logrotate man](https://linux.die.net/man/8/logrotate) ; we'll have to configure log for **each container** (as that's what we get: 1 file per container)

**Comment by kelson42** [comment]
Each day a log rotate and only 30 days retention.

**Comment by rgaudin** [comment]
Actually, because we are using containerd, logs are already rotated by containerd, using a kube-proxy configuration.
The defaults that we are using are:
- `containerLogMaxSize="10Mi"
- `containerLogMaxFiles=5`
- restarted containers keep previous one's log
- evicted containers removes logs

This is all fine and will gently be complemented by #5 

This leaves us with rotating only our on-disk nginx log (kiwix and openzim downloads)
