### ISSUE TITLE
TLS certificate for tracker.openzim.org seems not delivered

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#73]
```
$ openssl s_client -showcerts -connect tracker.openzim.org:6969
CONNECTED(00000003)
40D7ED69E77F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 328 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by rgaudin** [comment]
I believe [opentracker](https://erdgeist.org/arts/software/opentracker/) doesn't support SSL/TLS:

- there is no mention of it anywhere
- no option neither on the CLI
- source code doesn't reference neither `ssl` nor `tls` strings (actually there's one in [sync_daemon.pl](https://erdgeist.org/gitweb/opentracker/tree/sync_daemon.pl#n138) but that's for connecting to another tracker via https)

Remember this is an old project that received limited updates 18months ago

Closing as not supported

**Comment by rgaudin** [comment]
There is no reverse proxy. Port `6969` is exposed directly on both UDP and TCP.

Tracker speaks HTTP so we could add an nginx in the image and configure HTTPS proxying but we'd have to take care of the certificate handling ourselves and only work on TCP, leaving UDP for opentracker. https://nginx.org/en/docs/http/ngx_http_core_module.html#listen

That all seems like a lot of trouble. Is there an alternative to opentracker ?

**Comment by kelson42** [comment]
@rgaudin Please just secure the Mirrorbrain delivers links using `http` instead of `https` and we will be good.

**Comment by rgaudin** [comment]
Done in https://github.com/kiwix/k8s/commit/bfe9bf61bb1aaa27a42249af0944d71badbc31b2
