### ISSUE TITLE
Remove support of HTTP at library.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#90]
This would be replaced by a redirection to HTTPS

The main reason is that I worry about the security/concern for user not taking care (so they might be monitored in "demo" mode of library.kiwix.org).

**Comment by rgaudin** [comment]
Assign it to me should you decide to go forth with it. As listed elsewhere, current reasons not to enforce HTTPS:

- systems with broken date system (battery dead) are not able to use HTTPS. Google and many other services work (not WP though).
- can be (rarely) useful to check zimit-ZIMs behavior outside the Secure Context

**Comment by kelson42** [comment]
> * systems with broken date system (battery dead) are not able to use HTTPS. Google and many other services work (not WP though).

seems not significat enough case to counter balance the benefits.

> * can be (rarely) useful to check zimit-ZIMs behavior outside the Secure Context

We should keep dev.library.kiwix.org available via http for this.

@kelson42 please implement the redirect https -> https

**Comment by rgaudin** [comment]
> @kelson42 please implement the redirect https -> https

https://en.wikipedia.org/wiki/Sleep
