### ISSUE TITLE
How to get a quick index of the kiwix library?

### ISSUE THREAD

**Issue by jojo2357** [kiwix/k8s#95]
Following the instructions found here: https://download.kiwix.org/library/README

I followed `https://library.kiwix.org/catalog/v2/` to a nonexistent page; the documentation suggests that it is only for local kiwix archives, which is not helpful to me.

Going [here](https://library.kiwix.org) was helpful, but not in a machine readable format.

[This](https://download.kiwix.org/library/library_zim.xml) is perfect, but the base64 images make it obnoxiously large when all i want is a list of files without having to do a recursive search of the zim directory. (also deprecation warnings)

So my question then: how do i get a quick, machine-readable, low-overhead listing of all the zims available from kiwix?

Thanks \:)

**Comment by kelson42** [comment]
@jojo2357 Here is the doc you need IMO https://kiwix-tools.readthedocs.io/en/latest/kiwix-serve.html#catalog-v2-opds-api

**Comment by jojo2357** [comment]
I just realized that all the endpoint *other* than /catalog/v2 work as intended :roll_eyes: 

While im here, why does `https://library.kiwix.org/catalog/v2/entries?count=-1` not return archived results? [`https://download.kiwix.org/zim/wikipedia/`](https://download.kiwix.org/zim/wikipedia/) has both [wikipedia_en_100_2023-05.zim](https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_2023-05.zim) and [wikipedia_en_100_2023-06.zim](https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_2023-06.zim) but the api only acknowledges `wikipedia_en_100_2023-06`

**Comment by kelson42** [comment]
> While im here, why does https://library.kiwix.org/catalog/v2/entries?count=-1 not return archived results?

There os np concept of archive. We just one older version to avoid interruption of downloads at switch time (publishing of new version).

**Comment by jojo2357** [comment]
Alright, I will consider myself satisfied. thanks for the help
